services:
  - type: web
    name: hackrx-api
    runtime: python
    buildCommand: pip install --only-binary=:all: -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GROQ_API_KEY
        value: your_real_key_here
